### ISSUE TITLE
Norwegian detected as Deutch

### ISSUE THREAD

**Issue by evenfrost** [wooorm/franc#92] opened 2020-10-12 07:48 UTC
The following text

```
"Ble lokket pga det sto få 100 gratis uten innskudd.alt du må gjøre er å registrere deg.

Vel..nå har jeg prøvd,googlet osv... og uansett så vil dere at jeg skal registrere visa kortet og sette inn min innskudd...da er det ikke gratis spinn for kun registrering da 😡

Eller gjør jeg noe feil ? "
```
is detected as Deutch, though it's Norwegian and its length seems to be pretty sufficient.

**Comment by wooorm** [comment] 2020-10-12 07:59
Cannot reproduce, I’m pasting it [here](https://wooorm.com/franc/) and franc detects nynorsk:

**Comment by wooorm** [comment] 2020-10-18 17:20
Closing this as I can’t reproduce it

**Closed by wooorm** 2020-10-18 17:20 UTC

**Comment by evenfrost** [comment] 2020-10-22 09:20
My bad, I was using `franc-min` package which obviously doesn't support Norwegian. It works as expected.
